change-template: "* $TITLE (#$NUMBER) by @$AUTHOR"
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🌟Non-Breaking Changes'
    labels:
      - 'major'
  - title: '🌟 Minor Changes'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '📜 Documentation updates'
    labels:
      - 'documentation'
  - title: '🐛 Bug and hot fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🚒 Deprecations'
    labels:
      - 'deprecated'
exclude-labels:
  - 'skip-changelog'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Changes

  $CHANGES

  ## This release was made possible by the following contributors:

  $CONTRIBUTORS
